spring:
  profiles.active: dev

  application:
    name: usgs-service

  jackson:
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
server:
  port: 8088

logging:
  file: logs/usgs-service.log
  level:
    org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerMapping: TRACE

management:
  server:
    port: 8081